name: CPU End-to-End Test

on:
  workflow_dispatch: # Allows manual triggering or via Github API
    inputs:
      triggering_job_id:
        description: 'ID of the Kokoro job that triggered this workflow'
        required: false
  schedule:
    - cron: '0 9 * * *' # (UTC 9am everyday, and it corresponds to 2 am PDT everyday.)

permissions: {}

jobs:
  test-runner:
    strategy:
      matrix:
        runner: ["test-linux-n2-16", "test-linux-n2-32", "test-windows-n2-16"]
    runs-on: ${{ matrix.runner }}
    container: ${{ (contains(matrix.runner, 'test-linux') && 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:infrastructure-public-image-2c74567ee8e0') ||
                   (contains(matrix.runner, 'arm64') && 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build-arm64:infrastructure-public-image-8f4da9c96079') ||
                   (contains(matrix.runner, 'windows') && null) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: Simulate running a job on ${{ matrix.runner }}
        run: |
          echo "Starting a job on runner: ${{ matrix.runner }}..."
          sleep 30
          echo "Job finished on runner: ${{ matrix.runner }}."
