name: CPU End-to-End Test

on:
  workflow_dispatch: # Allows manual triggering or via Github API
    inputs:
      triggering_job_id:
        description: 'ID of the Kokoro job that triggered this workflow'
        required: false
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *' # (UTC 9am everyday, and it corresponds to 2 am PDT everyday.)

jobs:
  test-runner:
    strategy:
      matrix:
        runner: ["linux-x86-n2-16", "linux-arm64-c4a-16", "windows-x86-n2-16"]
    runs-on: ${{ matrix.runner }}
    container: ${{ (contains(matrix.runner, 'linux-x86') && 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest') ||
                   (contains(matrix.runner, 'linux-arm64') && 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build-arm64:latest') ||
                   (contains(matrix.runner, 'windows-x86') && null) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: Simulate running a job on ${{ matrix.runner }}
        run: |
          echo "Starting a job on runner: ${{ matrix.runner }}..."
          sleep 30
          echo "Job finished on runner: ${{ matrix.runner }}."
