name: Benchmarking Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'benchmarking/**'
      - '.github/workflows/benchmarking-tests.yml'
  workflow_dispatch:

permissions:
  contents: read

# Cancel any previous runs on the same branch when a new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bazel_tests:
    name: Run Bazel Tests
    runs-on: linux-x86-n2-16
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest@sha256:e1461af32bf27640ddbcde7c3e7a10f194142779e9ed3bba962040812e626a1c # ratchet:us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5
        with:
          persist-credentials: false
      - name: Run benchmarking Bazel tests
        run: |
          bazel test --test_output=errors //benchmarking/...
