name: Python Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # ratchet:astral-sh/ruff-action@v4.1.0
  format:
    name: Ruff Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # ratchet:astral-sh/ruff-action@v4.1.0
        with:
          args: "format --check --diff"
