# This workflow is an end-to-end integration test for the
# run-benchmarks.yml reusable workflow.
name: Benchmark workflow e2e test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'benchmarking/**'
      - '.github/workflows/run-benchmarks.yaml'
      - '.github/workflows/benchmark-workflow-e2e-test.yaml'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  run_e2e_test:
    name: Run e2e test of reusable benchmarking Workflow
    uses: ./.github/workflows/run-benchmarks.yaml
    with:
      registry_file: "benchmarking/e2e_test/test_registry.pbtxt"
      workflow_type: "PRESUBMIT"
