# A workflow to test buildifier composite action

name: Test CI Buildifier Action
# Run on pull_request
on:
  pull_request:
    paths:
    - ci_buildifier/**
    - tests/ci_buildifier/**
    - .github/workflows/test-ci-buildifier.yaml
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  run-buildifier:
    runs-on: "linux-x86-n2-16"
    container: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build:latest"
    timeout-minutes: 60
    if: |
      github.event.sender.type == 'User' ||
      contains(github.event.pull_request.body, 'RUN_BUILDIFIER')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: "Run buildifier action"
        uses: ./ci_buildifier/
