# A workflow to test waiting for SSH connections to the runner.
name: Connection Test
# Run on pull_request that is labeled as "optional_ci_tpu" or workflow dispatch
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'
# Cancel any previous iterations if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  wait-test:
    strategy:
      fail-fast: false
      matrix:
        runner: ["linux-x86-n2-16"]
        instances: ["1"]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    container:
      # TODO: Needs newer, light weight image
      image: index.docker.io/tensorflow/build@sha256:7fb38f0319bda36393cad7f40670aa22352b44421bb906f5cf34d543acd8e1d2 # ratchet:tensorflow/build:latest-python3.11
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # ratchet:actions/checkout@v4
      # Halt for connection if workflow dispatch is told to or if it is a retry with the label halt_on_retry
      - name: Wait For Connection
        uses: ./ci_connection/
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: Echo
        run: echo "Real job here..."
