# A workflow to test waiting for remote connections to the runner.
name: Connection Test
# Run on pull_request that is labeled as "optional_ci_tpu" or workflow dispatch
on:
  pull_request:
    paths:
    - ci_connection
    - .github/workflows/wait-for-connection-test.yaml
    branches:
      - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'
defaults:
  run:
    shell: bash
# Cancel any previous iterations if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  wait-test:
    strategy:
      fail-fast: false
      matrix:
        runner: ["linux-x86-g2-48-l4-4gpu"]
        instances: ["1"]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    container:
      image: "gcr.io/tensorflow-testing/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # ratchet:actions/checkout@v4
      - name: Echo
        run: |
          set -x
          echo "ipv6 enabled"
          cat /proc/sys/net/ipv6/conf/all/disable_ipv6
          echo "------------------------------- DONE -------------------------------"
      # Halt for connection if workflow dispatch is told to or if it is a retry with the label halt_on_retry
      - name: Wait For Connection
        uses: ./ci_connection/
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
